feat: add new workflow hint on submit btn
weweb-assets/ww-button pull request #17
Opened 2022-02-24 09:14 UTC by AlexisJC

On ajoute ici un workflowHint pour indiquer à l'utilisateur qu'il ne doit pas trigger depuis un bouton submit mais depuis le composant parent.

2022-02-24 09:52 UTC, AurelieV requested changes

2022-02-24 09:52 UTC, AurelieV commented on ww-config.js
> +                            wwLib.$store.dispatch('manager/resetSelectedObjects');
on évite de référencer le store en dehors de l'éditeur, il vaut mieux exposer une méthode qui abstrait cette couche (déselect, select, etc)

2022-02-24 09:52 UTC, AurelieV commented on ww-config.js
> +
je me demande si on devrait pas plutôt avoir une méthode selectParentByFlag ou qq chose comme ça dans l'éditeur, avec un param pour le message d'erreur

2022-03-02 13:40 UTC, AurelieV approved these changes

2022-03-07 18:17 UTC, Dams-d approved these changes

2022-03-07 18:17 UTC, Dams-d commented on ww-config.js
> +                    en: 'You should not trigger workflow on submit buttons',
Pas besoin de texte en fr

2022-03-08 16:41 UTC, Kramerbaf approved these changes

2022-03-08 16:41 UTC, merged